import {
  SIZE_PROFILES,
  createStatBlock,
  defaultStanceForKind,
  rectangularTokenBounds,
  statBlockHitPoints,
  type AbilityScores,
  type ChallengeRating,
  type CreatureSize,
  type CreatureSpeeds,
  type CreatureType,
  type TokenBlueprint,
  type TokenKind,
  type Trait,
  type Wallet,
} from "./types";

/**
 * Ready-to-play creatures transcribed from the Monster Manual, plus objects
 * built from the Dungeon Master's Guide tables.
 *
 * A stat block creature is described entirely by its type, size, and printed
 * numbers. It has no race, class, background, or level, because creature types
 * "have no rules of their own" (Monster Manual, "Statistics"). Armor class and
 * hit points are the values on the page rather than anything derived from the
 * gear it happens to be carrying.
 */

/** Ability scores in stat block order: STR, DEX, CON, INT, WIS, CHA. */
type AbilityLine = [number, number, number, number, number, number];

interface MonsterEntry {
  id: string;
  kind: TokenKind;
  name: string;
  creatureType: CreatureType;
  size: CreatureSize;
  /** Parenthetical tags after the type, such as "goblinoid" or "shapechanger". */
  tags?: string[];
  alignment: string;
  challenge: ChallengeRating;
  ac: number;
  armorNote?: string;
  hitDice: number;
  speeds?: Partial<CreatureSpeeds>;
  abilities: AbilityLine;
  saves?: Array<keyof AbilityScores>;
  /** Printed skill totals, not bonuses stacked on an ability modifier. */
  skills?: Record<string, number>;
  senses?: string[];
  languages?: string[];
  vulnerabilities?: string[];
  resistances?: string[];
  damageImmunities?: string[];
  conditionImmunities?: string[];
  /** Special traits, printed above the actions. */
  traits?: Array<[string, string]>;
  /** Actions, bonus actions, and reactions. */
  actions?: Array<[string, string]>;
  notes: string;
  wallet?: Wallet;
  /** Overrides the footprint implied by the creature's size. */
  width?: number;
  height?: number;
  sourcePage: number;
}

/** Muted token colors grouped by creature type, matching the app palette. */
const TYPE_COLORS: Record<CreatureType, string> = {
  aberration: "#777391",
  beast: "#6f7b83",
  celestial: "#7f7890",
  construct: "#6f7485",
  dragon: "#765462",
  elemental: "#637c79",
  fey: "#777391",
  fiend: "#765462",
  giant: "#7b687f",
  humanoid: "#68758a",
  monstrosity: "#7b687f",
  ooze: "#637c79",
  plant: "#6f7b83",
  undead: "#7b687f",
  object: "#78808f",
  other: "#78808f",
};

const OBJECT_NOTE =
  "Objects are immune to poison and psychic damage, and can't be affected by conditions.";

const MONSTERS: MonsterEntry[] = [
  // ---------------------------------------------------------------- humanoids
  {
    id: "builtin-goblin",
    kind: "enemy",
    name: "Goblin",
    creatureType: "humanoid",
    size: "small",
    tags: ["goblinoid"],
    alignment: "Neutral Evil",
    challenge: "1/4",
    ac: 15,
    armorNote: "leather armor, shield",
    hitDice: 2,
    abilities: [8, 14, 10, 10, 8, 8],
    skills: { Stealth: 6 },
    senses: ["Darkvision 60 ft."],
    languages: ["Common", "Goblin"],
    traits: [
      [
        "Nimble Escape",
        "Takes the Disengage or Hide action as a bonus action on each of its turns.",
      ],
    ],
    actions: [
      ["Scimitar", "Melee weapon attack, +4 to hit, reach 5 ft. Hit: 5 (1d6 + 2) slashing."],
      [
        "Shortbow",
        "Ranged weapon attack, +4 to hit, range 80/320 ft. Hit: 5 (1d6 + 2) piercing.",
      ],
    ],
    notes: "A cowardly skirmisher that swarms in numbers and flees the moment a fight turns.",
    sourcePage: 166,
  },
  {
    id: "builtin-goblin-boss",
    kind: "enemy",
    name: "Goblin Boss",
    creatureType: "humanoid",
    size: "small",
    tags: ["goblinoid"],
    alignment: "Neutral Evil",
    challenge: "1",
    ac: 17,
    armorNote: "chain shirt, shield",
    hitDice: 6,
    abilities: [10, 14, 10, 10, 8, 10],
    skills: { Stealth: 6 },
    senses: ["Darkvision 60 ft."],
    languages: ["Common", "Goblin"],
    traits: [
      [
        "Nimble Escape",
        "Takes the Disengage or Hide action as a bonus action on each of its turns.",
      ],
    ],
    actions: [
      ["Multiattack", "Makes two attacks, the second with disadvantage."],
      ["Scimitar", "Melee weapon attack, +4 to hit, reach 5 ft. Hit: 5 (1d6 + 2) slashing."],
      [
        "Javelin",
        "Melee or ranged weapon attack, +4 to hit, reach 5 ft. or range 30/120 ft. Hit: 5 (1d6 + 2) piercing.",
      ],
      [
        "Redirect Attack (Reaction)",
        "When targeted by an attack it can see, swaps places with a goblin within 5 ft., which becomes the target instead.",
      ],
    ],
    notes: "The biggest goblin in the lair, ruling by cruelty and using its kin as shields.",
    sourcePage: 166,
  },
  {
    id: "builtin-hobgoblin",
    kind: "enemy",
    name: "Hobgoblin",
    creatureType: "humanoid",
    size: "medium",
    tags: ["goblinoid"],
    alignment: "Lawful Evil",
    challenge: "1/2",
    ac: 18,
    armorNote: "chain mail, shield",
    hitDice: 2,
    abilities: [13, 12, 12, 10, 10, 9],
    senses: ["Darkvision 60 ft."],
    languages: ["Common", "Goblin"],
    traits: [
      [
        "Martial Advantage",
        "Once per turn, deals an extra 7 (2d6) damage to a creature it hits if an ally is within 5 ft. of that creature.",
      ],
    ],
    actions: [
      [
        "Longsword",
        "Melee weapon attack, +3 to hit, reach 5 ft. Hit: 5 (1d8 + 1) slashing, or 6 (1d10 + 1) two-handed.",
      ],
      [
        "Longbow",
        "Ranged weapon attack, +3 to hit, range 150/600 ft. Hit: 5 (1d8 + 1) piercing.",
      ],
    ],
    notes: "A disciplined soldier that fights in formation and never breaks ranks.",
    sourcePage: 186,
  },
  {
    id: "builtin-bugbear",
    kind: "enemy",
    name: "Bugbear",
    creatureType: "humanoid",
    size: "medium",
    tags: ["goblinoid"],
    alignment: "Chaotic Evil",
    challenge: "1",
    ac: 16,
    armorNote: "hide armor, shield",
    hitDice: 5,
    abilities: [15, 14, 13, 8, 11, 9],
    skills: { Stealth: 6, Survival: 2 },
    senses: ["Darkvision 60 ft."],
    languages: ["Common", "Goblin"],
    traits: [
      ["Brute", "A melee weapon deals one extra die of damage on a hit (already included)."],
      [
        "Surprise Attack",
        "If it surprises a creature and hits in the first round, the attack deals an extra 7 (2d6) damage.",
      ],
    ],
    actions: [
      [
        "Morningstar",
        "Melee weapon attack, +4 to hit, reach 5 ft. Hit: 11 (2d8 + 2) piercing.",
      ],
      [
        "Javelin",
        "Melee or ranged weapon attack, +4 to hit, reach 5 ft. or range 30/120 ft. Hit: 9 (2d6 + 2) piercing in melee, or 5 (1d6 + 2) at range.",
      ],
    ],
    notes: "A hulking ambusher that stalks prey in silence and opens with a devastating strike.",
    sourcePage: 33,
  },
  {
    id: "builtin-kobold",
    kind: "enemy",
    name: "Kobold",
    creatureType: "humanoid",
    size: "small",
    tags: ["kobold"],
    alignment: "Lawful Evil",
    challenge: "1/8",
    ac: 12,
    hitDice: 2,
    abilities: [7, 15, 9, 8, 7, 8],
    senses: ["Darkvision 60 ft."],
    languages: ["Common", "Draconic"],
    traits: [
      [
        "Sunlight Sensitivity",
        "In sunlight, has disadvantage on attack rolls and on sight-based Perception checks.",
      ],
      [
        "Pack Tactics",
        "Has advantage on an attack roll if an ally is within 5 ft. of the target and not incapacitated.",
      ],
    ],
    actions: [
      ["Dagger", "Melee weapon attack, +4 to hit, reach 5 ft. Hit: 4 (1d4 + 2) piercing."],
      [
        "Sling",
        "Ranged weapon attack, +4 to hit, range 30/120 ft. Hit: 4 (1d4 + 2) bludgeoning.",
      ],
    ],
    notes: "Weak alone and dangerous in swarms; favors traps, tunnels, and overwhelming numbers.",
    sourcePage: 195,
  },
  {
    id: "builtin-orc",
    kind: "enemy",
    name: "Orc",
    creatureType: "humanoid",
    size: "medium",
    tags: ["orc"],
    alignment: "Chaotic Evil",
    challenge: "1/2",
    ac: 13,
    armorNote: "hide armor",
    hitDice: 2,
    abilities: [16, 12, 16, 7, 11, 10],
    skills: { Intimidation: 2 },
    senses: ["Darkvision 60 ft."],
    languages: ["Common", "Orc"],
    traits: [
      [
        "Aggressive",
        "As a bonus action, moves up to its speed toward a hostile creature it can see.",
      ],
    ],
    actions: [
      [
        "Greataxe",
        "Melee weapon attack, +5 to hit, reach 5 ft. Hit: 9 (1d12 + 3) slashing.",
      ],
      [
        "Javelin",
        "Melee or ranged weapon attack, +5 to hit, reach 5 ft. or range 30/120 ft. Hit: 6 (1d6 + 3) piercing.",
      ],
    ],
    notes: "A savage raider that charges the nearest enemy and fights until it drops.",
    sourcePage: 246,
  },
  {
    id: "builtin-bandit",
    kind: "enemy",
    name: "Bandit",
    creatureType: "humanoid",
    size: "medium",
    tags: ["any race"],
    alignment: "Chaotic Neutral",
    challenge: "1/8",
    ac: 12,
    armorNote: "leather armor",
    hitDice: 2,
    abilities: [11, 12, 12, 10, 10, 10],
    languages: ["Common"],
    actions: [
      ["Scimitar", "Melee weapon attack, +3 to hit, reach 5 ft. Hit: 4 (1d6 + 1) slashing."],
      [
        "Light Crossbow",
        "Ranged weapon attack, +3 to hit, range 80/320 ft. Hit: 5 (1d8 + 1) piercing.",
      ],
    ],
    notes: "A desperate highway robber. Not all bandits are evil; many were driven to it.",
    sourcePage: 343,
  },

  // ------------------------------------------------------------------- undead
  {
    id: "builtin-skeleton",
    kind: "enemy",
    name: "Skeleton",
    creatureType: "undead",
    size: "medium",
    alignment: "Lawful Evil",
    challenge: "1/4",
    ac: 13,
    armorNote: "armor scraps",
    hitDice: 2,
    abilities: [10, 14, 15, 6, 8, 5],
    vulnerabilities: ["bludgeoning"],
    damageImmunities: ["poison"],
    conditionImmunities: ["Exhaustion", "Poisoned"],
    senses: ["Darkvision 60 ft."],
    languages: ["Understands the languages it knew in life but can't speak"],
    actions: [
      [
        "Shortsword",
        "Melee weapon attack, +4 to hit, reach 5 ft. Hit: 5 (1d6 + 2) piercing.",
      ],
      [
        "Shortbow",
        "Ranged weapon attack, +4 to hit, range 80/320 ft. Hit: 5 (1d6 + 2) piercing.",
      ],
    ],
    notes:
      "Animated bones following orders to the letter. Obeys literally and adapts poorly to surprises.",
    sourcePage: 272,
  },
  {
    id: "builtin-zombie",
    kind: "enemy",
    name: "Zombie",
    creatureType: "undead",
    size: "medium",
    alignment: "Neutral Evil",
    challenge: "1/4",
    ac: 8,
    hitDice: 3,
    speeds: { walk: 20 },
    abilities: [13, 6, 16, 3, 6, 5],
    saves: ["wis"],
    damageImmunities: ["poison"],
    conditionImmunities: ["Poisoned"],
    senses: ["Darkvision 60 ft."],
    languages: ["Understands the languages it knew in life but can't speak"],
    traits: [
      [
        "Undead Fortitude",
        "When reduced to 0 hit points by damage that isn't radiant or a critical hit, makes a Constitution save (DC 5 + damage taken) to drop to 1 hit point instead.",
      ],
    ],
    actions: [
      ["Slam", "Melee weapon attack, +3 to hit, reach 5 ft. Hit: 4 (1d6 + 1) bludgeoning."],
    ],
    notes: "Slow, mindless, and stubbornly hard to put down. Walks straight at the nearest living thing.",
    sourcePage: 316,
  },
  {
    id: "builtin-ghoul",
    kind: "enemy",
    name: "Ghoul",
    creatureType: "undead",
    size: "medium",
    alignment: "Chaotic Evil",
    challenge: "1",
    ac: 12,
    hitDice: 5,
    abilities: [13, 15, 10, 7, 10, 6],
    damageImmunities: ["poison"],
    conditionImmunities: ["Charmed", "Exhaustion", "Poisoned"],
    senses: ["Darkvision 60 ft."],
    languages: ["Common"],
    actions: [
      ["Bite", "Melee weapon attack, +2 to hit, reach 5 ft. Hit: 9 (2d6 + 2) piercing."],
      [
        "Claws",
        "Melee weapon attack, +4 to hit, reach 5 ft. Hit: 7 (2d4 + 2) slashing. A non-elf, non-undead target must succeed on a DC 10 Constitution save or be paralyzed for 1 minute, repeating the save at the end of each of its turns.",
      ],
    ],
    notes: "A ravenous corpse-eater whose claws lock victims in place for the rest of the pack.",
    sourcePage: 148,
  },

  // -------------------------------------------------------------------- beasts
  {
    id: "builtin-wolf",
    kind: "enemy",
    name: "Wolf",
    creatureType: "beast",
    size: "medium",
    alignment: "Unaligned",
    challenge: "1/4",
    ac: 13,
    armorNote: "natural armor",
    hitDice: 2,
    speeds: { walk: 40 },
    abilities: [12, 15, 12, 3, 12, 6],
    skills: { Perception: 3, Stealth: 4 },
    traits: [
      [
        "Keen Hearing and Smell",
        "Has advantage on Perception checks that rely on hearing or smell.",
      ],
      [
        "Pack Tactics",
        "Has advantage on an attack roll if an ally is within 5 ft. of the target and not incapacitated.",
      ],
    ],
    actions: [
      [
        "Bite",
        "Melee weapon attack, +4 to hit, reach 5 ft. Hit: 7 (2d4 + 2) piercing. The target must succeed on a DC 11 Strength save or be knocked prone.",
      ],
    ],
    notes: "Hunts in packs, circling to flank and drag prey down.",
    sourcePage: 341,
  },
  {
    id: "builtin-dire-wolf",
    kind: "enemy",
    name: "Dire Wolf",
    creatureType: "beast",
    size: "large",
    alignment: "Unaligned",
    challenge: "1",
    ac: 14,
    armorNote: "natural armor",
    hitDice: 5,
    speeds: { walk: 50 },
    abilities: [17, 15, 15, 3, 12, 7],
    skills: { Perception: 3, Stealth: 4 },
    traits: [
      [
        "Keen Hearing and Smell",
        "Has advantage on Perception checks that rely on hearing or smell.",
      ],
      [
        "Pack Tactics",
        "Has advantage on an attack roll if an ally is within 5 ft. of the target and not incapacitated.",
      ],
    ],
    actions: [
      [
        "Bite",
        "Melee weapon attack, +5 to hit, reach 5 ft. Hit: 10 (2d6 + 3) piercing. The target must succeed on a DC 13 Strength save or be knocked prone.",
      ],
    ],
    notes: "A horse-sized predator, often ridden as a mount by goblins and worg-keeping tribes.",
    sourcePage: 321,
  },
  {
    id: "builtin-giant-spider",
    kind: "enemy",
    name: "Giant Spider",
    creatureType: "beast",
    size: "large",
    alignment: "Unaligned",
    challenge: "1",
    ac: 14,
    armorNote: "natural armor",
    hitDice: 4,
    speeds: { walk: 30, climb: 30 },
    abilities: [14, 16, 12, 2, 11, 4],
    skills: { Stealth: 7 },
    senses: ["Blindsight 10 ft.", "Darkvision 60 ft."],
    traits: [
      ["Spider Climb", "Climbs difficult surfaces, including ceilings, without an ability check."],
      [
        "Web Sense",
        "While in contact with a web, knows the exact location of any other creature touching that web.",
      ],
      ["Web Walker", "Ignores movement restrictions caused by webbing."],
    ],
    actions: [
      [
        "Bite",
        "Melee weapon attack, +5 to hit, reach 5 ft. Hit: 7 (1d8 + 3) piercing, and a DC 11 Constitution save for 9 (2d8) poison damage, half on a success.",
      ],
      [
        "Web (Recharge 5-6)",
        "Ranged weapon attack, +5 to hit, range 30/60 ft. Hit: the target is restrained. Escape with a DC 12 Strength check, or destroy the webbing (AC 10, 5 hp, vulnerable to fire).",
      ],
    ],
    notes: "Lairs on ceilings and in web-choked crevices, dropping onto prey from above.",
    sourcePage: 328,
  },
  {
    id: "builtin-stirge",
    kind: "enemy",
    name: "Stirge",
    creatureType: "beast",
    size: "tiny",
    alignment: "Unaligned",
    challenge: "1/8",
    ac: 14,
    armorNote: "natural armor",
    hitDice: 1,
    speeds: { walk: 10, fly: 40 },
    abilities: [4, 16, 11, 2, 8, 6],
    senses: ["Darkvision 60 ft."],
    actions: [
      [
        "Blood Drain",
        "Melee weapon attack, +5 to hit, reach 5 ft. Hit: 5 (1d4 + 3) piercing, and the stirge attaches. While attached it doesn't attack; the target loses 5 (1d4 + 3) hit points at the start of each of the stirge's turns. It detaches after draining 10 hit points.",
      ],
    ],
    notes: "Little threat alone, but a swarm bleeds a party dry while they swat at them.",
    sourcePage: 284,
  },

  // ------------------------------------------------------------- monstrosities
  {
    id: "builtin-owlbear",
    kind: "enemy",
    name: "Owlbear",
    creatureType: "monstrosity",
    size: "large",
    alignment: "Unaligned",
    challenge: "3",
    ac: 13,
    armorNote: "natural armor",
    hitDice: 7,
    speeds: { walk: 40 },
    abilities: [20, 12, 17, 3, 12, 7],
    skills: { Perception: 3 },
    senses: ["Darkvision 60 ft."],
    traits: [
      [
        "Keen Sight and Smell",
        "Has advantage on Perception checks that rely on sight or smell.",
      ],
    ],
    actions: [
      ["Multiattack", "Makes two attacks: one with its beak and one with its claws."],
      ["Beak", "Melee weapon attack, +7 to hit, reach 5 ft. Hit: 10 (1d10 + 5) piercing."],
      ["Claws", "Melee weapon attack, +7 to hit, reach 5 ft. Hit: 14 (2d8 + 5) slashing."],
    ],
    notes: "Ill-tempered and relentless. Attacks anything it notices and pursues fleeing prey.",
    sourcePage: 249,
  },
  {
    id: "builtin-mimic",
    kind: "enemy",
    name: "Mimic",
    creatureType: "monstrosity",
    size: "medium",
    tags: ["shapechanger"],
    alignment: "True Neutral",
    challenge: "2",
    ac: 12,
    armorNote: "natural armor",
    hitDice: 9,
    speeds: { walk: 15 },
    abilities: [17, 12, 15, 5, 13, 8],
    skills: { Stealth: 5 },
    damageImmunities: ["acid"],
    conditionImmunities: ["Prone"],
    senses: ["Darkvision 60 ft."],
    traits: [
      ["Shapechanger", "Uses its action to polymorph into an object or back into its amorphous form."],
      [
        "Adhesive (Object Form Only)",
        "Adheres to anything that touches it. A Huge or smaller creature is also grappled (escape DC 13) with disadvantage on escape checks.",
      ],
      [
        "False Appearance (Object Form Only)",
        "While motionless, is indistinguishable from an ordinary object.",
      ],
      ["Grappler", "Has advantage on attack rolls against any creature it is grappling."],
    ],
    actions: [
      [
        "Pseudopod",
        "Melee weapon attack, +5 to hit, reach 5 ft. Hit: 7 (1d8 + 3) bludgeoning. In object form the target is also subjected to Adhesive.",
      ],
      [
        "Bite",
        "Melee weapon attack, +5 to hit, reach 5 ft. Hit: 7 (1d8 + 3) piercing plus 4 (1d8) acid.",
      ],
    ],
    notes: "Poses as a door or chest. Reward a Perception or Investigation check before anyone touches it.",
    sourcePage: 220,
  },

  // -------------------------------------------------------------------- giant
  {
    id: "builtin-ogre",
    kind: "enemy",
    name: "Ogre",
    creatureType: "giant",
    size: "large",
    alignment: "Chaotic Evil",
    challenge: "2",
    ac: 11,
    armorNote: "hide armor",
    hitDice: 7,
    speeds: { walk: 40 },
    abilities: [19, 8, 16, 5, 7, 7],
    senses: ["Darkvision 60 ft."],
    languages: ["Common", "Giant"],
    actions: [
      [
        "Greatclub",
        "Melee weapon attack, +6 to hit, reach 5 ft. Hit: 13 (2d8 + 4) bludgeoning.",
      ],
      [
        "Javelin",
        "Melee or ranged weapon attack, +6 to hit, reach 5 ft. or range 30/120 ft. Hit: 11 (2d6 + 4) piercing.",
      ],
    ],
    notes: "Enormous, dim, and quick to rage. Smashes whatever offends it until nothing is left.",
    sourcePage: 237,
  },

  // ---------------------------------------------------------------------- ooze
  {
    id: "builtin-gray-ooze",
    kind: "enemy",
    name: "Gray Ooze",
    creatureType: "ooze",
    size: "medium",
    alignment: "Unaligned",
    challenge: "1/2",
    ac: 8,
    hitDice: 3,
    speeds: { walk: 10, climb: 10 },
    abilities: [12, 6, 16, 1, 6, 2],
    skills: { Stealth: 2 },
    resistances: ["acid", "cold", "fire"],
    conditionImmunities: [
      "Blinded",
      "Charmed",
      "Deafened",
      "Exhaustion",
      "Frightened",
      "Prone",
    ],
    senses: ["Blindsight 60 ft. (blind beyond this radius)"],
    traits: [
      ["Amorphous", "Moves through a space as narrow as 1 inch wide without squeezing."],
      [
        "Corrode Metal",
        "A nonmagical metal weapon that hits it takes a cumulative -1 penalty to damage rolls, and is destroyed at -5. Eats through 2 inches of metal per round.",
      ],
      ["False Appearance", "While motionless, is indistinguishable from an oily pool or wet rock."],
    ],
    actions: [
      [
        "Pseudopod",
        "Melee weapon attack, +3 to hit, reach 5 ft. Hit: 4 (1d6 + 1) bludgeoning plus 7 (2d6) acid. Nonmagical metal armor worn by the target takes a cumulative -1 penalty to AC.",
      ],
    ],
    notes: "Looks like wet stone until it moves. Ruins metal gear even when the fight goes well.",
    sourcePage: 243,
  },

  // ----------------------------------------------------------------- construct
  {
    id: "builtin-animated-armor",
    kind: "enemy",
    name: "Animated Armor",
    creatureType: "construct",
    size: "medium",
    alignment: "Unaligned",
    challenge: "1",
    ac: 18,
    armorNote: "natural armor",
    hitDice: 6,
    speeds: { walk: 25 },
    abilities: [14, 11, 13, 1, 3, 1],
    damageImmunities: ["poison", "psychic"],
    conditionImmunities: [
      "Blinded",
      "Charmed",
      "Deafened",
      "Exhaustion",
      "Frightened",
      "Paralyzed",
      "Petrified",
      "Poisoned",
    ],
    senses: ["Blindsight 60 ft. (blind beyond this radius)"],
    traits: [
      [
        "Antimagic Susceptibility",
        "Incapacitated while in an antimagic field. If targeted by dispel magic, must succeed on a Constitution save against the caster's DC or fall unconscious for 1 minute.",
      ],
      [
        "False Appearance",
        "While motionless, is indistinguishable from a normal suit of armor.",
      ],
    ],
    actions: [
      ["Multiattack", "Makes two melee attacks."],
      ["Slam", "Melee weapon attack, +4 to hit, reach 5 ft. Hit: 5 (1d6 + 2) bludgeoning."],
    ],
    notes: "A hallway guardian that stands motionless until someone walks past it.",
    sourcePage: 19,
  },

  // --------------------------------------------------------------------- plant
  {
    id: "builtin-twig-blight",
    kind: "enemy",
    name: "Twig Blight",
    creatureType: "plant",
    size: "small",
    alignment: "Neutral Evil",
    challenge: "1/8",
    ac: 13,
    armorNote: "natural armor",
    hitDice: 1,
    speeds: { walk: 20 },
    abilities: [6, 13, 12, 4, 8, 3],
    skills: { Stealth: 3 },
    vulnerabilities: ["fire"],
    conditionImmunities: ["Blinded", "Deafened"],
    senses: ["Blindsight 60 ft. (blind beyond this radius)"],
    languages: ["Understands Common but can't speak"],
    traits: [
      ["False Appearance", "While motionless, is indistinguishable from a dead shrub."],
    ],
    actions: [
      ["Claws", "Melee weapon attack, +3 to hit, reach 5 ft. Hit: 3 (1d4 + 1) piercing."],
    ],
    notes: "A bundle of animate briars. Harmless alone, but thickets of them are a real hazard.",
    sourcePage: 32,
  },

  // ----------------------------------------------------------------------- fey
  {
    id: "builtin-sprite",
    kind: "enemy",
    name: "Sprite",
    creatureType: "fey",
    size: "tiny",
    alignment: "Neutral Good",
    challenge: "1/4",
    ac: 15,
    armorNote: "leather armor",
    hitDice: 1,
    speeds: { walk: 10, fly: 40 },
    abilities: [3, 18, 10, 14, 13, 11],
    skills: { Perception: 3, Stealth: 8 },
    languages: ["Common", "Elvish", "Sylvan"],
    actions: [
      ["Longsword", "Melee weapon attack, +2 to hit, reach 5 ft. Hit: 1 slashing."],
      [
        "Shortbow",
        "Ranged weapon attack, +6 to hit, range 40/160 ft. Hit: 1 piercing, and a DC 10 Constitution save or be poisoned for 1 minute. On a save of 5 or lower the target falls unconscious for the duration.",
      ],
      [
        "Heart Sight",
        "Touches a creature and knows its emotional state. On a failed DC 10 Charisma save, also learns its alignment.",
      ],
      [
        "Invisibility",
        "Turns invisible until it attacks, casts a spell, or its concentration ends.",
      ],
    ],
    notes: "A suspicious forest guardian. Reads intentions before deciding whether to help or vanish.",
    sourcePage: 283,
  },

  // --------------------------------------------------------------------- fiend
  {
    id: "builtin-imp",
    kind: "enemy",
    name: "Imp",
    creatureType: "fiend",
    size: "tiny",
    tags: ["devil", "shapechanger"],
    alignment: "Lawful Evil",
    challenge: "1",
    ac: 13,
    hitDice: 3,
    speeds: { walk: 20, fly: 40 },
    abilities: [6, 17, 13, 11, 12, 14],
    skills: { Deception: 4, Insight: 3, Persuasion: 4, Stealth: 5 },
    resistances: [
      "cold",
      "bludgeoning, piercing, and slashing from nonmagical weapons that aren't silvered",
    ],
    damageImmunities: ["fire", "poison"],
    conditionImmunities: ["Poisoned"],
    senses: ["Darkvision 120 ft."],
    languages: ["Infernal", "Common"],
    traits: [
      [
        "Shapechanger",
        "Polymorphs into a rat, raven, or spider form, or back. Its statistics are unchanged except for speed.",
      ],
      ["Devil's Sight", "Magical darkness doesn't impede its darkvision."],
      ["Magic Resistance", "Has advantage on saves against spells and other magical effects."],
    ],
    actions: [
      [
        "Sting",
        "Melee weapon attack, +5 to hit, reach 5 ft. Hit: 5 (1d4 + 3) piercing, and a DC 11 Constitution save for 10 (3d6) poison damage, half on a success.",
      ],
      [
        "Invisibility",
        "Turns invisible until it attacks or its concentration ends. Its equipment is invisible with it.",
      ],
    ],
    notes: "A scheming spy and tempter. Strikes from invisibility and flees to report rather than die.",
    sourcePage: 76,
  },

  // ------------------------------------------------------------------ elemental
  {
    id: "builtin-steam-mephit",
    kind: "enemy",
    name: "Steam Mephit",
    creatureType: "elemental",
    size: "small",
    alignment: "Neutral Evil",
    challenge: "1/4",
    ac: 10,
    hitDice: 6,
    speeds: { walk: 30, fly: 30 },
    abilities: [5, 11, 10, 11, 10, 12],
    damageImmunities: ["fire", "poison"],
    conditionImmunities: ["Poisoned"],
    senses: ["Darkvision 60 ft."],
    languages: ["Aquan", "Ignan"],
    traits: [
      [
        "Death Burst",
        "When it dies, explodes in steam. Each creature within 5 ft. must succeed on a DC 10 Dexterity save or take 4 (1d8) fire damage.",
      ],
      ["Innate Spellcasting (1/Day)", "Casts blur, requiring no material components (Charisma)."],
    ],
    actions: [
      [
        "Claws",
        "Melee weapon attack, +2 to hit, reach 5 ft. Hit: 2 (1d4) slashing plus 2 (1d4) fire.",
      ],
      [
        "Steam Breath (Recharge 6)",
        "Exhales a 15-foot cone of scalding steam. DC 10 Dexterity save for 4 (1d8) fire damage, half on a success.",
      ],
    ],
    notes: "An obnoxious, hissing nuisance that taunts its enemies and explodes when killed.",
    sourcePage: 217,
  },

  // -------------------------------------------------------------------- dragon
  {
    id: "builtin-white-dragon-wyrmling",
    kind: "enemy",
    name: "White Dragon Wyrmling",
    creatureType: "dragon",
    size: "medium",
    alignment: "Chaotic Evil",
    challenge: "2",
    ac: 16,
    armorNote: "natural armor",
    hitDice: 5,
    speeds: { walk: 30, burrow: 15, fly: 60, swim: 30 },
    abilities: [14, 10, 14, 5, 10, 11],
    saves: ["dex", "con", "wis", "cha"],
    skills: { Perception: 4, Stealth: 2 },
    damageImmunities: ["cold"],
    senses: ["Blindsight 10 ft.", "Darkvision 60 ft."],
    languages: ["Draconic"],
    actions: [
      [
        "Bite",
        "Melee weapon attack, +4 to hit, reach 5 ft. Hit: 7 (1d10 + 2) piercing plus 2 (1d4) cold.",
      ],
      [
        "Cold Breath (Recharge 5-6)",
        "Exhales an icy blast in a 15-foot cone. DC 12 Constitution save for 22 (5d8) cold damage, half on a success.",
      ],
    ],
    notes: "A vicious, dim-witted hatchling. Territorial and attacks without provocation.",
    sourcePage: 101,
  },

  // ---------------------------------------------------------------- aberration
  {
    id: "builtin-grell",
    kind: "enemy",
    name: "Grell",
    creatureType: "aberration",
    size: "medium",
    alignment: "Neutral Evil",
    challenge: "3",
    ac: 12,
    hitDice: 10,
    speeds: { walk: 10, fly: 30, hover: true },
    abilities: [15, 14, 13, 12, 11, 9],
    skills: { Perception: 4, Stealth: 6 },
    damageImmunities: ["lightning"],
    conditionImmunities: ["Blinded", "Prone"],
    senses: ["Blindsight 60 ft. (blind beyond this radius)"],
    languages: ["Grell"],
    actions: [
      ["Multiattack", "Makes two attacks: one with its tentacles and one with its beak."],
      [
        "Tentacles",
        "Melee weapon attack, +4 to hit, reach 10 ft. Hit: 7 (1d10 + 2) piercing, and a DC 11 Constitution save or be poisoned and paralyzed for 1 minute. The target is also grappled (escape DC 15), and restrained if Medium or smaller.",
      ],
      ["Beak", "Melee weapon attack, +4 to hit, reach 5 ft. Hit: 7 (2d4 + 2) piercing."],
    ],
    notes: "A floating, silent brain-and-tentacles horror that hovers in darkness above corridors.",
    sourcePage: 172,
  },

  // ----------------------------------------------------------------- celestial
  {
    id: "builtin-pegasus",
    kind: "npc",
    name: "Pegasus",
    creatureType: "celestial",
    size: "large",
    alignment: "Chaotic Good",
    challenge: "2",
    ac: 12,
    hitDice: 7,
    speeds: { walk: 60, fly: 90 },
    abilities: [18, 15, 16, 10, 15, 13],
    saves: ["dex", "wis", "cha"],
    skills: { Perception: 6 },
    languages: ["Understands Celestial, Common, Elvish, and Sylvan but can't speak"],
    actions: [
      ["Hooves", "Melee weapon attack, +6 to hit, reach 5 ft. Hit: 11 (2d6 + 4) bludgeoning."],
    ],
    notes: "Shy and as intelligent as a person. Can't be broken or tamed, only befriended.",
    sourcePage: 250,
  },

  // ------------------------------------------------------------ nonplayer NPCs
  {
    id: "builtin-commoner",
    kind: "npc",
    name: "Commoner",
    creatureType: "humanoid",
    size: "medium",
    tags: ["any race"],
    alignment: "True Neutral",
    challenge: "0",
    ac: 10,
    hitDice: 1,
    abilities: [10, 10, 10, 10, 10, 10],
    languages: ["Common"],
    actions: [
      ["Club", "Melee weapon attack, +2 to hit, reach 5 ft. Hit: 2 (1d4) bludgeoning."],
    ],
    notes:
      "Peasants, servants, merchants, and artisans. Knows local rumors and gets out of the way of trouble.",
    sourcePage: 345,
  },
  {
    id: "builtin-guard",
    kind: "npc",
    name: "Guard",
    creatureType: "humanoid",
    size: "medium",
    tags: ["any race"],
    alignment: "Lawful Neutral",
    challenge: "1/8",
    ac: 16,
    armorNote: "chain shirt, shield",
    hitDice: 2,
    abilities: [13, 12, 12, 10, 11, 10],
    skills: { Perception: 2 },
    languages: ["Common"],
    actions: [
      [
        "Spear",
        "Melee or ranged weapon attack, +3 to hit, reach 5 ft. or range 20/60 ft. Hit: 4 (1d6 + 1) piercing.",
      ],
    ],
    notes: "City watch, gate sentry, or hired muscle. Calls for reinforcements before fighting alone.",
    sourcePage: 347,
  },
  {
    id: "builtin-acolyte",
    kind: "npc",
    name: "Acolyte",
    creatureType: "humanoid",
    size: "medium",
    tags: ["any race"],
    alignment: "Lawful Good",
    challenge: "1/4",
    ac: 10,
    hitDice: 2,
    abilities: [10, 10, 10, 10, 14, 11],
    skills: { Medicine: 4, Religion: 2 },
    languages: ["Common"],
    traits: [
      [
        "Spellcasting",
        "1st-level spellcaster (Wisdom, save DC 12, +4 to hit). Cantrips: light, sacred flame, thaumaturgy. 1st level (3 slots): bless, cure wounds, sanctuary.",
      ],
    ],
    actions: [
      ["Club", "Melee weapon attack, +2 to hit, reach 5 ft. Hit: 2 (1d4) bludgeoning."],
    ],
    notes: "A junior temple servant with minor divine magic. Useful for healing and holy ground.",
    sourcePage: 342,
  },
  {
    id: "builtin-priest",
    kind: "npc",
    name: "Priest",
    creatureType: "humanoid",
    size: "medium",
    tags: ["any race"],
    alignment: "Lawful Neutral",
    challenge: "2",
    ac: 13,
    armorNote: "chain shirt",
    hitDice: 5,
    speeds: { walk: 25 },
    abilities: [10, 10, 12, 13, 16, 13],
    skills: { Medicine: 7, Persuasion: 3, Religion: 4 },
    languages: ["Common"],
    traits: [
      [
        "Divine Eminence",
        "As a bonus action, expends a spell slot to make its melee weapon attacks deal an extra 10 (3d6) radiant damage until the end of the turn.",
      ],
      [
        "Spellcasting",
        "5th-level spellcaster (Wisdom, save DC 13, +5 to hit). Cantrips: light, sacred flame, thaumaturgy. 1st (4 slots): cure wounds, guiding bolt, sanctuary. 2nd (3 slots): lesser restoration, spiritual weapon. 3rd (2 slots): dispel magic, spirit guardians.",
      ],
    ],
    actions: [
      ["Mace", "Melee weapon attack, +2 to hit, reach 5 ft. Hit: 3 (1d6) bludgeoning."],
    ],
    notes: "Spiritual leader of a temple, often holding real political influence in the community.",
    sourcePage: 348,
  },
  {
    id: "builtin-scout",
    kind: "npc",
    name: "Scout",
    creatureType: "humanoid",
    size: "medium",
    tags: ["any race"],
    alignment: "True Neutral",
    challenge: "1/2",
    ac: 13,
    armorNote: "leather armor",
    hitDice: 3,
    abilities: [11, 14, 12, 11, 13, 11],
    skills: { Nature: 4, Perception: 5, Stealth: 6, Survival: 5 },
    languages: ["Common"],
    traits: [
      [
        "Keen Hearing and Sight",
        "Has advantage on Perception checks that rely on hearing or sight.",
      ],
    ],
    actions: [
      ["Multiattack", "Makes two melee attacks or two ranged attacks."],
      [
        "Shortsword",
        "Melee weapon attack, +4 to hit, reach 5 ft. Hit: 5 (1d6 + 2) piercing.",
      ],
      [
        "Longbow",
        "Ranged weapon attack, +4 to hit, range 150/600 ft. Hit: 6 (1d8 + 2) piercing.",
      ],
    ],
    notes: "A hunter and tracker for hire. Works as a guide, bounty hunter, or military eyes.",
    sourcePage: 349,
  },
  {
    id: "builtin-spy",
    kind: "npc",
    name: "Spy",
    creatureType: "humanoid",
    size: "medium",
    tags: ["any race"],
    alignment: "True Neutral",
    challenge: "1",
    ac: 12,
    hitDice: 6,
    abilities: [10, 15, 10, 12, 14, 16],
    skills: {
      Deception: 5,
      Insight: 4,
      Investigation: 5,
      Perception: 6,
      Persuasion: 5,
      "Sleight of Hand": 4,
      Stealth: 4,
    },
    languages: ["Common"],
    traits: [
      ["Cunning Action", "Uses a bonus action to Dash, Disengage, or Hide on each of its turns."],
      [
        "Sneak Attack (1/Turn)",
        "Deals an extra 7 (2d6) damage on a weapon hit made with advantage, or when an ally is within 5 ft. of the target.",
      ],
    ],
    actions: [
      ["Multiattack", "Makes two melee attacks."],
      [
        "Shortsword",
        "Melee weapon attack, +4 to hit, reach 5 ft. Hit: 5 (1d6 + 2) piercing.",
      ],
      [
        "Hand Crossbow",
        "Ranged weapon attack, +4 to hit, range 30/120 ft. Hit: 5 (1d6 + 2) piercing.",
      ],
    ],
    notes: "Gathers information for a patron. Would rather die than compromise their employer.",
    sourcePage: 349,
  },
  {
    id: "builtin-noble",
    kind: "npc",
    name: "Noble",
    creatureType: "humanoid",
    size: "medium",
    tags: ["any race"],
    alignment: "Lawful Neutral",
    challenge: "1/8",
    ac: 15,
    armorNote: "breastplate",
    hitDice: 2,
    abilities: [11, 12, 11, 12, 14, 16],
    skills: { Deception: 5, Insight: 4, Persuasion: 5 },
    languages: ["Common"],
    actions: [
      ["Rapier", "Melee weapon attack, +3 to hit, reach 5 ft. Hit: 5 (1d8 + 1) piercing."],
      [
        "Parry (Reaction)",
        "Adds 2 to its AC against one melee attack that would hit it, provided it can see the attacker and is wielding a melee weapon.",
      ],
    ],
    notes: "Wealth and connections make them dangerous well beyond their combat statistics.",
    sourcePage: 348,
  },
  {
    id: "builtin-knight",
    kind: "npc",
    name: "Knight",
    creatureType: "humanoid",
    size: "medium",
    tags: ["any race"],
    alignment: "Lawful Good",
    challenge: "3",
    ac: 18,
    armorNote: "plate",
    hitDice: 8,
    abilities: [16, 11, 14, 11, 11, 15],
    saves: ["con", "wis"],
    languages: ["Common"],
    traits: [["Brave", "Has advantage on saving throws against being frightened."]],
    actions: [
      ["Multiattack", "Makes two melee attacks."],
      ["Greatsword", "Melee weapon attack, +5 to hit, reach 5 ft. Hit: 10 (2d6 + 3) slashing."],
      [
        "Heavy Crossbow",
        "Ranged weapon attack, +2 to hit, range 100/400 ft. Hit: 5 (1d10) piercing.",
      ],
      [
        "Leadership (Recharges after a Short or Long Rest)",
        "For 1 minute, a nonhostile creature within 30 ft. that can hear it adds a d4 to an attack roll or saving throw. Ends if the knight is incapacitated.",
      ],
      [
        "Parry (Reaction)",
        "Adds 2 to its AC against one melee attack that would hit it, provided it can see the attacker and is wielding a melee weapon.",
      ],
    ],
    notes: "Sworn to a ruler, order, or cause. Usually travels with squires and hirelings.",
    sourcePage: 347,
  },
  {
    id: "builtin-veteran",
    kind: "npc",
    name: "Veteran",
    creatureType: "humanoid",
    size: "medium",
    tags: ["any race"],
    alignment: "True Neutral",
    challenge: "3",
    ac: 17,
    armorNote: "splint",
    hitDice: 9,
    abilities: [16, 13, 14, 10, 11, 10],
    skills: { Athletics: 5, Perception: 2 },
    languages: ["Common"],
    actions: [
      [
        "Multiattack",
        "Makes two longsword attacks, plus a shortsword attack if it has one drawn.",
      ],
      [
        "Longsword",
        "Melee weapon attack, +5 to hit, reach 5 ft. Hit: 7 (1d8 + 3) slashing, or 8 (1d10 + 3) two-handed.",
      ],
      ["Shortsword", "Melee weapon attack, +5 to hit, reach 5 ft. Hit: 6 (1d6 + 3) piercing."],
      [
        "Heavy Crossbow",
        "Ranged weapon attack, +3 to hit, range 100/400 ft. Hit: 5 (1d10) piercing.",
      ],
    ],
    notes: "A professional fighter, retired soldier, or sellsword. Fights for pay or conviction.",
    sourcePage: 350,
  },
  {
    id: "builtin-thug",
    kind: "enemy",
    name: "Thug",
    creatureType: "humanoid",
    size: "medium",
    tags: ["any race"],
    alignment: "Neutral Evil",
    challenge: "1/2",
    ac: 11,
    armorNote: "leather armor",
    hitDice: 5,
    abilities: [15, 11, 14, 10, 10, 11],
    skills: { Intimidation: 2 },
    languages: ["Common"],
    traits: [
      [
        "Pack Tactics",
        "Has advantage on an attack roll if an ally is within 5 ft. of the target and not incapacitated.",
      ],
    ],
    actions: [
      ["Multiattack", "Makes two melee attacks."],
      ["Mace", "Melee weapon attack, +4 to hit, reach 5 ft. Hit: 5 (1d6 + 2) bludgeoning."],
      [
        "Heavy Crossbow",
        "Ranged weapon attack, +2 to hit, range 100/400 ft. Hit: 5 (1d10) piercing.",
      ],
    ],
    notes: "A hired enforcer who works in groups and leans on intimidation before violence.",
    sourcePage: 350,
  },
  {
    id: "builtin-bandit-captain",
    kind: "enemy",
    name: "Bandit Captain",
    creatureType: "humanoid",
    size: "medium",
    tags: ["any race"],
    alignment: "Chaotic Neutral",
    challenge: "2",
    ac: 15,
    armorNote: "studded leather",
    hitDice: 10,
    abilities: [15, 16, 14, 14, 11, 14],
    saves: ["str", "dex", "wis"],
    skills: { Athletics: 4, Deception: 4 },
    languages: ["Common"],
    actions: [
      [
        "Multiattack",
        "Makes three melee attacks: two with its scimitar and one with its dagger. Or two ranged dagger attacks.",
      ],
      ["Scimitar", "Melee weapon attack, +5 to hit, reach 5 ft. Hit: 6 (1d6 + 3) slashing."],
      [
        "Dagger",
        "Melee or ranged weapon attack, +5 to hit, reach 5 ft. or range 20/60 ft. Hit: 5 (1d4 + 3) piercing.",
      ],
      [
        "Parry (Reaction)",
        "Adds 2 to its AC against one melee attack that would hit it, provided it can see the attacker and is wielding a melee weapon.",
      ],
    ],
    notes: "Craves infamy above treasure. Flattery and reputation go further than threats.",
    sourcePage: 344,
  },
  {
    id: "builtin-berserker",
    kind: "enemy",
    name: "Berserker",
    creatureType: "humanoid",
    size: "medium",
    tags: ["any race"],
    alignment: "Chaotic Neutral",
    challenge: "2",
    ac: 13,
    armorNote: "hide armor",
    hitDice: 9,
    abilities: [16, 12, 17, 9, 11, 9],
    languages: ["Common"],
    traits: [
      [
        "Reckless",
        "At the start of its turn, can gain advantage on all melee weapon attacks this turn, but attacks against it have advantage until its next turn.",
      ],
    ],
    actions: [
      ["Greataxe", "Melee weapon attack, +5 to hit, reach 5 ft. Hit: 9 (1d12 + 3) slashing."],
    ],
    notes: "Seeks conflict wherever it can be found. Trades its own safety for raw aggression.",
    sourcePage: 344,
  },
  {
    id: "builtin-cultist",
    kind: "enemy",
    name: "Cultist",
    creatureType: "humanoid",
    size: "medium",
    tags: ["any race"],
    alignment: "Chaotic Evil",
    challenge: "1/8",
    ac: 12,
    armorNote: "leather armor",
    hitDice: 2,
    abilities: [11, 12, 10, 10, 11, 10],
    skills: { Deception: 2, Religion: 2 },
    languages: ["Common"],
    traits: [
      ["Dark Devotion", "Has advantage on saving throws against being charmed or frightened."],
    ],
    actions: [
      ["Scimitar", "Melee weapon attack, +3 to hit, reach 5 ft. Hit: 4 (1d6 + 1) slashing."],
    ],
    notes: "Sworn to a demon lord or archdevil, and usually hiding that fact from their neighbors.",
    sourcePage: 345,
  },
  {
    id: "builtin-tribal-warrior",
    kind: "enemy",
    name: "Tribal Warrior",
    creatureType: "humanoid",
    size: "medium",
    tags: ["any race"],
    alignment: "True Neutral",
    challenge: "1/8",
    ac: 12,
    armorNote: "hide armor",
    hitDice: 2,
    abilities: [13, 11, 12, 8, 11, 8],
    languages: ["Common"],
    traits: [
      [
        "Pack Tactics",
        "Has advantage on an attack roll if an ally is within 5 ft. of the target and not incapacitated.",
      ],
    ],
    actions: [
      [
        "Spear",
        "Melee or ranged weapon attack, +3 to hit, reach 5 ft. or range 20/60 ft. Hit: 4 (1d6 + 1) piercing, or 5 (1d8 + 1) two-handed in melee.",
      ],
    ],
    notes: "Lives beyond civilization by hunting and fishing, and follows the will of a chief.",
    sourcePage: 350,
  },
  {
    id: "builtin-druid",
    kind: "npc",
    name: "Druid",
    creatureType: "humanoid",
    size: "medium",
    tags: ["any race"],
    alignment: "True Neutral",
    challenge: "2",
    ac: 11,
    hitDice: 5,
    abilities: [10, 12, 13, 12, 15, 11],
    skills: { Medicine: 4, Nature: 3, Perception: 4 },
    languages: ["Druidic", "Common"],
    traits: [
      [
        "Spellcasting",
        "4th-level spellcaster (Wisdom, save DC 12, +4 to hit). Cantrips: druidcraft, produce flame, shillelagh. 1st (4 slots): entangle, longstrider, speak with animals, thunderwave. 2nd (3 slots): animal messenger, barkskin.",
      ],
    ],
    actions: [
      [
        "Quarterstaff",
        "Melee weapon attack, +2 to hit (+4 with shillelagh), reach 5 ft. Hit: 3 (1d6) bludgeoning, or 4 (1d8) with shillelagh or two hands.",
      ],
    ],
    notes: "Protects the wild from monsters and encroaching civilization alike. AC 16 with barkskin.",
    sourcePage: 346,
  },
  {
    id: "builtin-mage",
    kind: "npc",
    name: "Mage",
    creatureType: "humanoid",
    size: "medium",
    tags: ["any race"],
    alignment: "True Neutral",
    challenge: "6",
    ac: 12,
    hitDice: 9,
    abilities: [9, 14, 11, 17, 12, 11],
    saves: ["int", "wis"],
    skills: { Arcana: 6, History: 6 },
    languages: ["Common"],
    traits: [
      [
        "Spellcasting",
        "9th-level spellcaster (Intelligence, save DC 14, +6 to hit). Cantrips: fire bolt, light, mage hand, prestidigitation. 1st (4 slots): detect magic, mage armor, magic missile, shield. 2nd (3 slots): misty step, suggestion. 3rd (3 slots): counterspell, fireball, fly. 4th (3 slots): greater invisibility, ice storm. 5th (1 slot): cone of cold.",
      ],
    ],
    actions: [
      [
        "Dagger",
        "Melee or ranged weapon attack, +5 to hit, reach 5 ft. or range 20/60 ft. Hit: 4 (1d4 + 2) piercing.",
      ],
    ],
    notes: "AC 15 with mage armor. A serious threat at range; likely has a familiar nearby.",
    sourcePage: 347,
  },

  // ------------------------------------------------------------------- objects
  {
    id: "builtin-object-wooden-door",
    kind: "object",
    name: "Wooden Door",
    creatureType: "object",
    size: "medium",
    alignment: "Unaligned",
    challenge: "0",
    ac: 15,
    armorNote: "wood",
    hitDice: 4,
    speeds: { walk: 0 },
    abilities: [12, 1, 10, 0, 0, 0],
    damageImmunities: ["poison", "psychic"],
    notes: `A sturdy wooden door. ${OBJECT_NOTE}`,
    sourcePage: 246,
  },
  {
    id: "builtin-object-iron-door",
    kind: "object",
    name: "Iron Door",
    creatureType: "object",
    size: "medium",
    alignment: "Unaligned",
    challenge: "0",
    ac: 19,
    armorNote: "iron",
    hitDice: 4,
    speeds: { walk: 0 },
    abilities: [16, 1, 10, 0, 0, 0],
    damageImmunities: ["poison", "psychic"],
    notes: `A reinforced iron door. ${OBJECT_NOTE}`,
    sourcePage: 246,
  },
  {
    id: "builtin-object-chest",
    kind: "object",
    name: "Treasure Chest",
    creatureType: "object",
    size: "small",
    alignment: "Unaligned",
    challenge: "0",
    ac: 15,
    armorNote: "wood",
    hitDice: 3,
    speeds: { walk: 0 },
    abilities: [10, 1, 10, 0, 0, 0],
    damageImmunities: ["poison", "psychic"],
    wallet: { copper: 0, silver: 0, gold: 25 },
    notes: `A banded wooden chest. ${OBJECT_NOTE}`,
    sourcePage: 246,
  },
  {
    id: "builtin-object-barrel",
    kind: "object",
    name: "Barrel",
    creatureType: "object",
    size: "medium",
    alignment: "Unaligned",
    challenge: "0",
    ac: 15,
    armorNote: "wood",
    hitDice: 1,
    speeds: { walk: 0 },
    abilities: [10, 1, 10, 0, 0, 0],
    damageImmunities: ["poison", "psychic"],
    notes: `A fragile storage barrel. ${OBJECT_NOTE}`,
    sourcePage: 246,
  },
  {
    id: "builtin-object-crate",
    kind: "object",
    name: "Crate",
    creatureType: "object",
    size: "medium",
    alignment: "Unaligned",
    challenge: "0",
    ac: 15,
    armorNote: "wood",
    hitDice: 4,
    speeds: { walk: 0 },
    abilities: [10, 1, 10, 0, 0, 0],
    damageImmunities: ["poison", "psychic"],
    notes: `A heavy shipping crate. ${OBJECT_NOTE}`,
    sourcePage: 246,
  },
  {
    id: "builtin-object-chair",
    kind: "object",
    name: "Chair",
    creatureType: "object",
    size: "medium",
    alignment: "Unaligned",
    challenge: "0",
    ac: 15,
    armorNote: "wood",
    hitDice: 1,
    speeds: { walk: 0 },
    abilities: [8, 1, 10, 0, 0, 0],
    damageImmunities: ["poison", "psychic"],
    notes: `A simple wooden chair. ${OBJECT_NOTE}`,
    sourcePage: 246,
  },
  {
    id: "builtin-object-table",
    kind: "object",
    name: "Table",
    creatureType: "object",
    size: "large",
    alignment: "Unaligned",
    challenge: "0",
    ac: 15,
    armorNote: "wood",
    hitDice: 5,
    speeds: { walk: 0 },
    abilities: [12, 1, 10, 0, 0, 0],
    damageImmunities: ["poison", "psychic"],
    width: 2,
    height: 1,
    notes: `A long wooden table, sturdy enough to overturn for cover. ${OBJECT_NOTE}`,
    sourcePage: 246,
  },
  {
    id: "builtin-object-statue",
    kind: "object",
    name: "Stone Statue",
    creatureType: "object",
    size: "large",
    alignment: "Unaligned",
    challenge: "0",
    ac: 17,
    armorNote: "stone",
    hitDice: 5,
    speeds: { walk: 0 },
    abilities: [16, 1, 10, 0, 0, 0],
    damageImmunities: ["poison", "psychic"],
    notes: `A carved stone statue. ${OBJECT_NOTE}`,
    sourcePage: 246,
  },
  {
    id: "builtin-object-portcullis",
    kind: "object",
    name: "Iron Portcullis",
    creatureType: "object",
    size: "large",
    alignment: "Unaligned",
    challenge: "0",
    ac: 19,
    armorNote: "iron",
    hitDice: 5,
    speeds: { walk: 0 },
    abilities: [18, 1, 10, 0, 0, 0],
    damageImmunities: ["poison", "psychic"],
    width: 2,
    height: 1,
    notes: `A heavy iron grate. Lifting it is a DC 20 Strength check. ${OBJECT_NOTE}`,
    sourcePage: 246,
  },
  {
    id: "builtin-object-window",
    kind: "object",
    name: "Glass Window",
    creatureType: "object",
    size: "large",
    alignment: "Unaligned",
    challenge: "0",
    ac: 13,
    armorNote: "glass",
    hitDice: 1,
    speeds: { walk: 0 },
    abilities: [4, 1, 10, 0, 0, 0],
    damageImmunities: ["poison", "psychic"],
    width: 2,
    height: 1,
    notes: `A large pane of glass. Shatters easily and loudly. ${OBJECT_NOTE}`,
    sourcePage: 246,
  },
];

function toTraits(entries: Array<[string, string]> | undefined, prefix: string): Trait[] {
  return (entries ?? []).map(([name, description], index) => ({
    id: `${prefix}-${index}`,
    name,
    description,
  }));
}

function blueprintFor(entry: MonsterEntry): TokenBlueprint {
  const abilities: AbilityScores = {
    str: entry.abilities[0],
    dex: entry.abilities[1],
    con: entry.abilities[2],
    int: entry.abilities[3],
    wis: entry.abilities[4],
    cha: entry.abilities[5],
  };
  const statBlock = createStatBlock({
    tags: entry.tags ?? [],
    alignment: entry.alignment,
    challenge: entry.challenge,
    armorNote: entry.armorNote ?? "",
    hitDice: entry.hitDice,
    speeds: entry.speeds,
    saveProficiencies: entry.saves ?? [],
    senses: entry.senses ?? [],
    languages: entry.languages ?? [],
    vulnerabilities: entry.vulnerabilities ?? [],
    resistances: entry.resistances ?? [],
    damageImmunities: entry.damageImmunities ?? [],
    conditionImmunities: entry.conditionImmunities ?? [],
    sourcePage: entry.sourcePage,
  });
  const maxHp = statBlockHitPoints(statBlock, entry.size, abilities.con);
  const footprint = SIZE_PROFILES[entry.size].cells;
  const width = entry.width ?? footprint;
  const height = entry.height ?? footprint;

  return {
    id: entry.id,
    source: "built-in",
    kind: entry.kind,
    name: entry.name,
    color: TYPE_COLORS[entry.creatureType],
    stance: defaultStanceForKind(entry.kind),
    visualScale: 1,
    notes: entry.notes,
    // A stat block creature has no ancestry: its type and numbers are the whole build.
    raceId: "",
    subraceId: "",
    classId: "",
    subclassId: "",
    backgroundId: "",
    race: "",
    subrace: "",
    className: "",
    subclass: "",
    backgroundName: "",
    ruleChoices: {},
    abilityImprovements: [],
    creatureType: entry.creatureType,
    size: entry.size,
    level: 1,
    hp: maxHp,
    maxHp,
    ac: entry.ac,
    abilities,
    skills: Object.entries(entry.skills ?? {}).map(([name, bonus]) => ({
      id: `${entry.id}-skill-${name.toLowerCase().replace(/\s+/g, "-")}`,
      name,
      bonus,
    })),
    traits: toTraits(entry.traits, `${entry.id}-trait`),
    features: toTraits(entry.actions, `${entry.id}-action`),
    inventory: [],
    wallet: entry.wallet ?? { copper: 0, silver: 0, gold: 0 },
    statuses: [],
    statBlock,
    width,
    height,
    bounds: rectangularTokenBounds(width, height),
  };
}

export const HANDBOOK_MONSTERS: TokenBlueprint[] = MONSTERS.map(blueprintFor);
