import {
  DEFAULT_ABILITIES,
  rectangularTokenBounds,
  type CreatureMechanics,
  type TokenBlueprint,
  type TokenKind,
} from "./types";

type BlueprintBase = Omit<TokenBlueprint, "bounds" | keyof CreatureMechanics> &
  Partial<CreatureMechanics>;

const BUILT_IN_TOKEN_BLUEPRINTS_BASE: BlueprintBase[] = [
  {
    id: "builtin-enemy-goblin-scout",
    source: "built-in",
    kind: "enemy",
    name: "Goblin Scout",
    creatureType: "humanoid",
    color: "#765462",
    maxHp: 7,
    ac: 13,
    skills: [{ id: "builtin-goblin-stealth", name: "Stealth", bonus: 6 }],
    inventory: [
      {
        id: "builtin-goblin-dagger",
        libraryItemId: "item-dagger",
        name: "Dagger",
        qty: 1,
        notes: "",
        equipped: true,
      },
    ],
    notes: "A quick skirmisher that prefers cover and ambushes.",
    width: 1,
    height: 1,
  },
  {
    id: "builtin-enemy-skeleton",
    source: "built-in",
    kind: "enemy",
    name: "Skeleton",
    creatureType: "undead",
    color: "#7b687f",
    maxHp: 13,
    ac: 13,
    skills: [],
    inventory: [
      {
        id: "builtin-skeleton-bow",
        libraryItemId: "item-shortbow",
        name: "Shortbow",
        qty: 1,
        notes: "",
        equipped: true,
      },
    ],
    notes: "An undead guard driven by simple commands.",
    width: 1,
    height: 1,
  },
  {
    id: "builtin-enemy-dire-wolf",
    source: "built-in",
    kind: "enemy",
    name: "Dire Wolf",
    color: "#765462",
    maxHp: 37,
    ac: 14,
    skills: [
      { id: "builtin-wolf-perception", name: "Perception", bonus: 3 },
      { id: "builtin-wolf-stealth", name: "Stealth", bonus: 4 },
    ],
    inventory: [],
    notes: "A large predator with keen senses.",
    width: 2,
    height: 2,
  },
  {
    id: "builtin-npc-villager",
    source: "built-in",
    kind: "npc",
    name: "Villager",
    color: "#68758a",
    maxHp: 4,
    ac: 10,
    skills: [],
    inventory: [],
    notes: "A local resident with ordinary knowledge of the area.",
    width: 1,
    height: 1,
  },
  {
    id: "builtin-npc-guard",
    source: "built-in",
    kind: "npc",
    name: "Guard",
    color: "#637c79",
    maxHp: 11,
    ac: 16,
    skills: [{ id: "builtin-guard-perception", name: "Perception", bonus: 2 }],
    inventory: [
      {
        id: "builtin-guard-spear",
        libraryItemId: "item-spear",
        name: "Spear",
        qty: 1,
        notes: "",
        equipped: true,
      },
      {
        id: "builtin-guard-shield",
        libraryItemId: "item-shield",
        name: "Shield",
        qty: 1,
        notes: "",
        equipped: true,
      },
    ],
    notes: "A trained watch member equipped for patrol.",
    width: 1,
    height: 1,
  },
  {
    id: "builtin-npc-merchant",
    source: "built-in",
    kind: "npc",
    name: "Merchant",
    color: "#777391",
    maxHp: 4,
    ac: 10,
    skills: [
      { id: "builtin-merchant-insight", name: "Insight", bonus: 4 },
      { id: "builtin-merchant-persuasion", name: "Persuasion", bonus: 5 },
    ],
    inventory: [
      {
        id: "builtin-merchant-goods",
        libraryItemId: "item-trade-goods",
        name: "Trade Goods",
        qty: 8,
        notes: "",
      },
    ],
    notes: "A traveling trader with useful goods and local rumors.",
    width: 1,
    height: 1,
  },
  {
    id: "builtin-object-door",
    source: "built-in",
    kind: "object",
    name: "Door",
    color: "#6f7485",
    maxHp: 15,
    ac: 12,
    skills: [],
    inventory: [],
    notes: "A sturdy wooden door.",
    width: 1,
    height: 1,
  },
  {
    id: "builtin-object-chest",
    source: "built-in",
    kind: "object",
    name: "Chest",
    color: "#7b687f",
    maxHp: 10,
    ac: 12,
    skills: [],
    inventory: [],
    wallet: { copper: 0, silver: 0, gold: 25 },
    notes: "A closed storage chest.",
    width: 1,
    height: 1,
  },
  {
    id: "builtin-object-chair",
    source: "built-in",
    kind: "object",
    name: "Chair",
    color: "#78808f",
    maxHp: 5,
    ac: 10,
    skills: [],
    inventory: [],
    notes: "A simple wooden chair.",
    width: 1,
    height: 1,
  },
  {
    id: "builtin-object-table",
    source: "built-in",
    kind: "object",
    name: "Table",
    color: "#78808f",
    maxHp: 12,
    ac: 10,
    skills: [],
    inventory: [],
    notes: "A rectangular wooden table.",
    width: 2,
    height: 1,
  },
];

export const BUILT_IN_TOKEN_BLUEPRINTS: TokenBlueprint[] =
  BUILT_IN_TOKEN_BLUEPRINTS_BASE.map((blueprint) => ({
    raceId: "",
    subraceId: "",
    classId: "",
    subclassId: "",
    backgroundId: "",
    race: "",
    subrace: "",
    className: "",
    subclass: "",
    backgroundName: "",
    ruleChoices: {},
    creatureType: blueprint.kind === "enemy" ? "beast" : "humanoid",
    size: "medium",
    level: 1,
    hp: blueprint.maxHp ?? 0,
    maxHp: blueprint.maxHp ?? 0,
    ac: blueprint.ac ?? 10,
    abilities: { ...DEFAULT_ABILITIES },
    skills: [],
    traits: [],
    features: [],
    inventory: [],
    wallet: { copper: 0, silver: 0, gold: 0 },
    statuses: [],
    ...blueprint,
    bounds: rectangularTokenBounds(blueprint.width, blueprint.height),
  }));

export function createBlankTokenBlueprint(kind: TokenKind): TokenBlueprint {
  return {
    id: crypto.randomUUID(),
    source: "custom",
    kind,
    name: kind === "enemy" ? "New Enemy" : kind === "npc" ? "New NPC" : "New Object",
    color: kind === "enemy" ? "#765462" : kind === "npc" ? "#68758a" : "#78808f",
    raceId: "",
    subraceId: "",
    classId: "",
    subclassId: "",
    backgroundId: "",
    race: "",
    subrace: "",
    className: "",
    subclass: "",
    backgroundName: "",
    ruleChoices: {},
    creatureType: kind === "enemy" ? "beast" : "humanoid",
    size: "medium",
    level: 1,
    hp: kind === "object" ? 0 : 10,
    maxHp: kind === "object" ? 0 : 10,
    ac: kind === "object" ? 0 : 10,
    abilities: { ...DEFAULT_ABILITIES },
    skills: [],
    traits: [],
    features: [],
    inventory: [],
    wallet: { copper: 0, silver: 0, gold: 0 },
    statuses: [],
    notes: "",
    width: 1,
    height: 1,
    bounds: rectangularTokenBounds(1, 1),
  };
}
